exclude .git

diff --git a/src/cnc/flavors/aws/lambda-lite/1/build/build_functions.sh.j2 b/src/cnc/flavors/aws/lambda-lite/1/build/build_functions.sh.j2
--- a/src/cnc/flavors/aws/lambda-lite/1/build/build_functions.sh.j2
+++ b/src/cnc/flavors/aws/lambda-lite/1/build/build_functions.sh.j2
@@ -56,12 +56,12 @@ build_{{ service.name }} () {
 
   if [ -d "$source_dir" ]; then
     echo "Source is a directory: $source_dir"
-    (cd "$source_dir" && zip -r "$output_file" . ) || { echo "Error creating ZIP file"; exit 1; }
+    (cd "$source_dir" && zip -r "$output_file" . -x "*.git*") || { echo "Error creating ZIP file"; exit 1; }
   elif [ -f "$source_dir" ]; then
     echo "Source is a file: $source_dir"
     base_name=$(basename "$source_dir")
     dir_name=$(dirname "$source_dir")
-    (cd "$dir_name" && zip -r "$output_file" "$base_name") || { echo "Error creating ZIP file"; exit 1; }
+    (cd "$dir_name" && zip -r "$output_file" "$base_name" -x "*.git*") || { echo "Error creating ZIP file"; exit 1; }
   else
     echo "Error: Source path is not valid: $source_dir"
     exit 1
