Toolbox - dont fail if unable to copy gcloud config (#119)

diff --git a/src/cnc/flavors/gcp/shared/toolbox/Dockerfile.j2 b/src/cnc/flavors/gcp/shared/toolbox/Dockerfile.j2
--- a/src/cnc/flavors/gcp/shared/toolbox/Dockerfile.j2
+++ b/src/cnc/flavors/gcp/shared/toolbox/Dockerfile.j2
@@ -1,7 +1,7 @@
 FROM {{ service.image_for_tag(toolbox.tag_for_service(service.name)) }}
 
 COPY .config/gcloud /_cnc_temp/gcloud
-RUN mkdir -p ~/.config/gcloud && cp -r /_cnc_temp/gcloud/* ~/.config/gcloud
+RUN mkdir -p ~/.config/gcloud && cp -r /_cnc_temp/gcloud/* ~/.config/gcloud || echo "Unable to copy gcloud config... skipping"
 
 # GOOGLE_APPLICATION_CREDENTIALS will be set to this filepath
 # when appropriate. see: main.sh.j2
