Adjustments PR | Deploy | Separate modifications in PR | Just PR Flavor Lambda lite

diff --git a/src/cnc/flavors/aws/lambda-lite/1/deploy/deploy_functions.sh.j2 b/src/cnc/flavors/aws/lambda-lite/1/deploy/deploy_functions.sh.j2
--- a/src/cnc/flavors/aws/lambda-lite/1/deploy/deploy_functions.sh.j2
+++ b/src/cnc/flavors/aws/lambda-lite/1/deploy/deploy_functions.sh.j2
@@ -33,6 +33,12 @@ if [ -z "$name_lambda" ] || [ -z "$output_dir" ] || [ -z "$region" ]; then
   exit 1
 fi
 
+# Backup the current Lambda function code
+echo "Backing up current function code for lambda function $name_lambda"
+aws lambda get-function --function-name "$name_lambda" --region "$region" > current_lambda_function.json
+zip_file_url=$(jq -r '.Code.Location' current_lambda_function.json)
+curl -o current_lambda_function.zip "$zip_file_url"
+
 # Deploying lambda function using AWS CLI
 echo "Deploying lambda function $name_lambda with ZIP file at $output_dir in region $region"
 
@@ -52,13 +58,23 @@ fi
 
 # Function to wait for the Lambda function to be in Active state
 wait_for_active() {
+  local max_retries=20
+  local retry_count=0
+  
   while true; do
     state=$(aws lambda get-function-configuration --function-name "$name_lambda" --region "$region" --query 'State' --output text)
     if [ "$state" == "Active" ]; then
       break
     fi
-    echo "Waiting for lambda function $name_lambda to be Active..."
+    
+    if [ $retry_count -ge $max_retries ]; then
+      echo "Lambda function $name_lambda did not become Active after $max_retries attempts."
+      exit 1
+    fi
+    
+    echo "Waiting for lambda function $name_lambda to be Active... (Attempt: $((retry_count + 1))/$max_retries)"
     sleep 3
+    retry_count=$((retry_count + 1))
   done
 }
 
@@ -80,29 +96,41 @@ exit_code=$?
 if [ $exit_code -eq 0 ]; then
   echo "Environment variables for lambda function $name_lambda updated successfully"
 else
-  echo "Error updating environment variables for lambda function $name_lambda. Rolling back to previous environment variables."
+  echo "Error updating environment variables for lambda function $name_lambda. Rolling back to previous environment variables and function code."
   
   # Rollback to previous environment variables
   rollback_exit_code=0
   echo "$current_env_vars" > current_env_vars.json
   aws lambda update-function-configuration --function-name "$name_lambda" --environment "file://current_env_vars.json" --region "$region" --no-cli-pager || rollback_exit_code=$?
-
+  
   if [ $rollback_exit_code -eq 0 ]; then
     echo "Rollback to previous environment variables successful."
   else
     echo "Error rolling back to previous environment variables. Manual intervention might be required."
   fi
+  
+  # Rollback to previous function code
+  aws lambda update-function-code --function-name "$name_lambda" --zip-file "fileb://current_lambda_function.zip" --region "$region" --no-cli-pager || rollback_exit_code=$?
+
+  if [ $rollback_exit_code -eq 0 ]; then
+    echo "Rollback to previous function code successful."
+  else
+    echo "Error rolling back to previous function code. Manual intervention might be required."
+  fi
 
   # Cleanup
   rm $env_vars_file
   rm current_env_vars.json
+  rm current_lambda_function.json
+  rm current_lambda_function.zip
 
   exit $exit_code
 fi
 
 # Cleanup
 rm $env_vars_file
-
+rm current_lambda_function.json
+rm current_lambda_function.zip
 
 # Exit with the captured exit code
 exit $exit_code
