FIX: Partial Ajustsments from PR Comments

diff --git a/src/cnc/flavors/aws/lambda-lite/1/deploy/deploy_functions.sh.j2 b/src/cnc/flavors/aws/lambda-lite/1/deploy/deploy_functions.sh.j2
--- a/src/cnc/flavors/aws/lambda-lite/1/deploy/deploy_functions.sh.j2
+++ b/src/cnc/flavors/aws/lambda-lite/1/deploy/deploy_functions.sh.j2
@@ -5,7 +5,6 @@ name_lambda="{{ service.instance_name }}"
 output_dir="{{ service.environment.collection.config_files_path }}/build/{{ service.instance_name }}_lambda_function.zip"
 region="{{ service.environment.collection.region }}"
 
-
 # Validation echos
 echo "Validating variables for service {{ service.instance_name }}..."
 echo "name_lambda: $name_lambda"
@@ -24,13 +23,15 @@ echo "Deploying lambda function $name_lambda with ZIP file at $output_dir in reg
 # Lambda deployment command using AWS CLI
 aws lambda update-function-code --function-name "$name_lambda" --zip-file "fileb://$output_dir" --region "$region" --no-cli-pager
 
+# Capturing the exit status of the aws command
+exit_code=$?
+
 # Checking the exit status of the aws command
-if [ $? -eq 0 ]; then
+if [ $exit_code -eq 0 ]; then
   echo "Lambda function $name_lambda updated successfully"
 else
   echo "Error updating lambda function $name_lambda."
-  exit 1
 fi
 
-# Example usage
-echo "Lambda deployment script completed for service {{ service.instance_name }}."
+# Exit with the captured exit code
+exit $exit_code
