Adjustments Comments in PR + Combine Resources flavors

diff --git a/src/cnc/flavors/aws/lambda-lite/1/deploy/deploy_functions.sh.j2 b/src/cnc/flavors/aws/lambda-lite/1/deploy/deploy_functions.sh.j2
--- a/src/cnc/flavors/aws/lambda-lite/1/deploy/deploy_functions.sh.j2
+++ b/src/cnc/flavors/aws/lambda-lite/1/deploy/deploy_functions.sh.j2
@@ -11,7 +11,6 @@ echo "name_lambda: $name_lambda"
 echo "output_dir: $output_dir"
 echo "region: $region"
 
-
 env_vars_file="env_vars.json"
 echo "Creating environment variables file $env_vars_file..."
 
@@ -51,6 +50,25 @@ else
   exit $exit_code
 fi
 
+# Function to wait for the Lambda function to be in Active state
+wait_for_active() {
+  while true; do
+    state=$(aws lambda get-function-configuration --function-name "$name_lambda" --region "$region" --query 'State' --output text)
+    if [ "$state" == "Active" ]; then
+      break
+    fi
+    echo "Waiting for lambda function $name_lambda to be Active..."
+    sleep 3
+  done
+}
+
+# Wait for the function to be active before updating environment variables
+wait_for_active
+
+# Backup the current environment variables
+echo "Backing up current environment variables for lambda function $name_lambda"
+current_env_vars=$(aws lambda get-function-configuration --function-name "$name_lambda" --region "$region" --query 'Environment' --output json)
+
 # Updating the lambda function configuration to add environment variables
 echo "Updating environment variables for lambda function $name_lambda"
 aws lambda update-function-configuration --function-name "$name_lambda" --environment "file://$env_vars_file" --region "$region" --no-cli-pager
@@ -62,11 +80,29 @@ exit_code=$?
 if [ $exit_code -eq 0 ]; then
   echo "Environment variables for lambda function $name_lambda updated successfully"
 else
-  echo "Error updating environment variables for lambda function $name_lambda."
+  echo "Error updating environment variables for lambda function $name_lambda. Rolling back to previous environment variables."
+  
+  # Rollback to previous environment variables
+  rollback_exit_code=0
+  echo "$current_env_vars" > current_env_vars.json
+  aws lambda update-function-configuration --function-name "$name_lambda" --environment "file://current_env_vars.json" --region "$region" --no-cli-pager || rollback_exit_code=$?
+
+  if [ $rollback_exit_code -eq 0 ]; then
+    echo "Rollback to previous environment variables successful."
+  else
+    echo "Error rolling back to previous environment variables. Manual intervention might be required."
+  fi
+
+  # Cleanup
+  rm $env_vars_file
+  rm current_env_vars.json
+
+  exit $exit_code
 fi
 
 # Cleanup
 rm $env_vars_file
+
 
 # Exit with the captured exit code
 exit $exit_code
