more fixes

diff --git a/src/cnc/flavors/aws/lambda-lite/1/deploy/deploy_functions.sh.j2 b/src/cnc/flavors/aws/lambda-lite/1/deploy/deploy_functions.sh.j2
--- a/src/cnc/flavors/aws/lambda-lite/1/deploy/deploy_functions.sh.j2
+++ b/src/cnc/flavors/aws/lambda-lite/1/deploy/deploy_functions.sh.j2
@@ -68,6 +68,32 @@ wait_for_active() {
 }
 
 deploy_{{ service.name }} () {
+  echo "ZIP Lambda function code..."
+
+  source_dir="{{ service.build.context }}"
+  output_dir="{{ deployer.rendered_files_path }}"
+  output_file="$output_dir/{{ service.instance_name }}_lambda_function.zip"
+
+  if [ -d "$source_dir" ]; then
+    echo "Source is a directory: $source_dir"
+    (cd "$source_dir" && zip -r "$output_file" . -x "*.git*") || { echo "Error creating ZIP file"; exit 1; }
+  elif [ -f "$source_dir" ]; then
+    echo "Source is a file: $source_dir"
+    base_name=$(basename "$source_dir")
+    dir_name=$(dirname "$source_dir")
+    (cd "$dir_name" && zip -r "$output_file" "$base_name" -x "*.git*") || { echo "Error creating ZIP file"; exit 1; }
+  else
+    echo "Error: Source path is not valid: $source_dir"
+    exit 1
+  fi
+
+  if [ -f "$output_file" ]; then
+    echo "ZIP file created successfully at $output_file"
+  else
+    echo "Error: ZIP file was not created at $output_file"
+    exit 1
+  fi
+
   # Assigning variables
   name_lambda="{{ service.instance_name }}"
   output_dir="{{ deployer.rendered_files_path }}/{{ service.instance_name }}_lambda_function.zip"
